openapi: 3.1.0
x-stoplight:
  id: vvog01xfr675i
info:
  title: TestAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: wytodi4kcczbx
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: 82gqtxcwbgh9u
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: nhtvcl4ynkr6r
  /users/test:
    get:
      summary: testGet
      tags: []
      responses:
        '100':
          description: Continue
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    x-stoplight:
                      id: sps759hfbd67i
                  test:
                    type: string
                    x-stoplight:
                      id: e9todqpajji5q
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Time:
                    type: integer
                    x-stoplight:
                      id: sdc02brzr75i3
                  Lane:
                    x-stoplight:
                      id: 3jvy7n42h2588
                    type: array
                    items: {}
                  Distance:
                    type: number
                    x-stoplight:
                      id: z6u2ewjgyahqg
        '301':
          description: Moved Permanently
          content:
            application/json:
              schema:
                type: object
                properties:
                  lane:
                    type: string
                    x-stoplight:
                      id: oji949xp1ceej
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  Name1:
                    type: string
                    x-stoplight:
                      id: f3v845ykhmnh1
      operationId: get-users-test
      x-stoplight:
        id: 7ya8ahuezf8m6
      parameters:
        - schema:
            type: string
          in: query
          name: Name
          description: Test
        - schema:
            type: string
          in: query
          name: Address
          description: OPP
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: 3zt9591eh8yfx
        firstName:
          type: string
          x-stoplight:
            id: zkthmff000t8x
        lastName:
          type: string
          x-stoplight:
            id: icyaxcgxc2ugb
        email:
          type: string
          format: email
          x-stoplight:
            id: 9itqma28we4zb
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: 56ea68is5qip6
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: r5fdj5m021ws2
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: nfsp3plbin3de
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: s9pcutjsduff0
